name: C/C++ CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: deps
      run: sudo apt-get install build-essential libssl-dev libpcap-dev libcurl4-openssl-dev
    - name: configure
      run: ./configure --enable-gzip
    - name: make
      run: make clean;make
    - uses: actions/upload-artifact@v4
      with:
        name: executables
        path: /home/runner/work/joy/joy/bin/
